### PR TITLE
Added benchmark results

### PR DESCRIPTION
**Pull request by cmelchior**
OrmLite test data is now inserted in one transaction.
Added benchmark results for 1.000 objects as we believe that is the most realistic use case.

@realm/java 
@bmunkholm

### CODE REVIEW

**Comment by kneth** [comment]
I wonder why the ORMs are faster than SQLite.

**Comment by cmelchior** [comment]
Possible reasons could be throttling. It is a long test (15 minutes), so thermals might be a problem.
I also have results for 1000 objects that look more like what you would expect for an overall picture

**Comment by cmelchior** [comment]
Any objections against me merging this?
@realm/java 
@bmunkholm

**Comment by beeender** [comment]
You PR froze my browser .... I guess I can only do :+1:

**Comment by bmunkholm** [comment]
+1

**Comment by kneth** [comment]
@cmelchior 1000 objects are probably more realistic. The count and sum benchmarks are still about two orders of magnatude above the timer's resolution so I'm fine with the results.

**Pull request merged**
